package runtime

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

const (
	DefaultTardigradeBinaryName = "tardigrade"
)

type Tardigrade struct {
	Runner     Runner
	BinaryPath string
	ConfigFile string
	WorkDir    string
}

type TardigradeConfigOptions struct {
	ListenPort  int
	PidFile     string
	PublicDir   string
	UpstreamURL string
}

func RenderTardigradeConfig(options TardigradeConfigOptions) string {
	options = normalizeTardigradeConfigOptions(options)

	return fmt.Sprintf(`# Generated by bare-systems. Edit edge.yml and .env, then rerender.
pid %s;
listen %d;
server_name localhost;

root %s;
try_files $uri /index.html;

location = /health {
    return 200 ok;
}

location = /bearclaw/health {
    proxy_pass %s/up;
}

location / {
    proxy_pass %s;
}
`, options.PidFile, options.ListenPort, options.PublicDir, options.UpstreamURL, options.UpstreamURL)
}

func WriteTardigradeConfig(path string, options TardigradeConfigOptions) error {
	normalized := normalizeTardigradeConfigOptions(options)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create Tardigrade config directory: %w", err)
	}
	if err := os.MkdirAll(normalized.PublicDir, 0o755); err != nil {
		return fmt.Errorf("create Tardigrade public directory: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(normalized.PidFile), 0o755); err != nil {
		return fmt.Errorf("create Tardigrade state directory: %w", err)
	}
	data := []byte(RenderTardigradeConfig(normalized))
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write Tardigrade config %s: %w", path, err)
	}
	return nil
}

func normalizeTardigradeConfigOptions(options TardigradeConfigOptions) TardigradeConfigOptions {
	if options.ListenPort <= 0 {
		options.ListenPort = 80
	}
	if strings.TrimSpace(options.PidFile) == "" {
		options.PidFile = "/var/run/tardigrade.pid"
	}
	if strings.TrimSpace(options.PublicDir) == "" {
		options.PublicDir = "/var/lib/tardigrade/public"
	}
	if strings.TrimSpace(options.UpstreamURL) == "" {
		options.UpstreamURL = "http://127.0.0.1:8080"
	}
	options.PidFile = strings.TrimSpace(options.PidFile)
	options.PublicDir = strings.TrimSpace(options.PublicDir)
	options.UpstreamURL = strings.TrimRight(strings.TrimSpace(options.UpstreamURL), "/")
	return options
}

func (t Tardigrade) Validate(ctx context.Context) (Result, error) {
	return t.run(ctx, "validate", "-c", t.ConfigFile)
}

func (t Tardigrade) StartOrReload(ctx context.Context) (Result, error) {
	status, err := t.Status(ctx)
	if err == nil && tardigradeStatusRunning(status.Stdout) {
		return t.Reload(ctx)
	}
	return t.run(ctx, "run", "-c", t.ConfigFile, "--daemon")
}

func (t Tardigrade) StopIfRunning(ctx context.Context) (Result, error) {
	status, err := t.Status(ctx)
	if err == nil && tardigradeStatusStopped(status.Stdout) {
		return status, nil
	}
	return t.Stop(ctx)
}

func (t Tardigrade) Reload(ctx context.Context) (Result, error) {
	return t.run(ctx, "reload", "-c", t.ConfigFile)
}

func (t Tardigrade) Stop(ctx context.Context) (Result, error) {
	return t.run(ctx, "stop", "-c", t.ConfigFile)
}

func (t Tardigrade) Status(ctx context.Context) (Result, error) {
	return t.run(ctx, "status", "-c", t.ConfigFile)
}

func (t Tardigrade) run(ctx context.Context, args ...string) (Result, error) {
	runner := t.Runner
	if runner == nil {
		runner = ExecRunner{}
	}
	binary := strings.TrimSpace(t.BinaryPath)
	if binary == "" {
		binary = DefaultTardigradeBinaryName
	}
	command := Command{Name: binary, Args: args, Dir: t.WorkDir}
	result, err := runner.Run(ctx, command)
	return result, CommandError(command, result, err)
}

func TardigradeUpstreamURL(bindAddress string, port string) string {
	host := strings.TrimSpace(bindAddress)
	if host == "" || host == "0.0.0.0" {
		host = "127.0.0.1"
	}
	resolvedPort := strings.TrimSpace(port)
	if resolvedPort == "" {
		resolvedPort = "8080"
	}
	return "http://" + host + ":" + resolvedPort
}

func TardigradeConfigPath(projectRoot string) string {
	return filepath.Join(projectRoot, "tardigrade", "tardigrade.conf")
}

func TardigradePublicDir(projectRoot string) string {
	return filepath.Join(projectRoot, "tardigrade", "public")
}

func TardigradePidFile(projectRoot string) string {
	return filepath.Join(projectRoot, "state", "tardigrade.pid")
}

func TardigradeListenPort(value string) int {
	port, err := strconv.Atoi(strings.TrimSpace(value))
	if err != nil || port <= 0 {
		return 80
	}
	return port
}

func tardigradeStatusRunning(output string) bool {
	return strings.Contains(strings.ToLower(output), "status: running")
}

func tardigradeStatusStopped(output string) bool {
	lower := strings.ToLower(output)
	return strings.Contains(lower, "status: stopped")
}
